import type { NextPage } from 'next'
import Head from 'next/head'
import HeaderTemplate from '../components/templates/header/HeaderTemplate'
import CarouselTemplate from '../components/templates/carousel/CarouselTemplate'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderTemplate sampleTextProp="Example header"></HeaderTemplate>
      <CarouselTemplate sampleTextProp="testing carousel"></CarouselTemplate>
    </div>
  )
}

export default Home
